all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 10.0.0.200
          ansible_port: 62222
          ansible_user: erik
          ansible_ssh_private_key_file: ~/.ssh/proxmox_key
