---
# Container-Start und Überwachung
# Startet Container und wartet auf vollständige Betriebsbereitschaft

- name: "Starte Container {{ container_id }} ({{ container_hostname }})"
  shell: "pct start {{ container_id }}"
  register: container_start_result
  tags: [container_start]

- name: "Warte auf Container-Start (max {{ container_start_retries * container_start_delay }}s)"
  shell: "pct status {{ container_id }}"
  register: startup_status_check
  until: "'running' in startup_status_check.stdout"
  retries: "{{ container_start_retries }}"
  delay: "{{ container_start_delay }}"
  tags: [startup_wait]

- name: "Warte auf Netzwerk-Initialisierung"
  pause:
    seconds: 5
    prompt: "Warte auf Netzwerk-Setup im Container..."
  tags: [network_wait]

- name: "Setze sicheres Root-Passwort"
  shell: |
    pct exec {{ container_id }} -- bash -c "echo 'root:{{ container_password }}' | chpasswd"
  register: password_result
  no_log: true
  tags: [password_setup, security]

- name: "Ermittle Container-IP-Adresse"
  shell: |
    pct exec {{ container_id }} -- ip addr show eth0 | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1 | head -1
  register: container_ip_result
  failed_when: false
  changed_when: false
  retries: 3
  delay: 2
  tags: [ip_detection]

- name: "Ermittle Container-MAC-Adresse"
  shell: |
    pct config {{ container_id }} | grep -E '^net0:' | grep -o 'hwaddr=[^,]*' | cut -d= -f2
  register: container_mac_result
  changed_when: false
  tags: [mac_detection]

- name: "Sammle Container-Status-Informationen"
  shell: "pct list | grep '^{{ container_id }} '"
  register: container_info
  changed_when: false
  tags: [status_info]
