# Container-Start und Status-Ueberwachung
# Startet den Container und wartet, bis er vollstaendig betriebsbereit (bleibt)

- name: "Starte Container {{ container_id }}"
  shell: "pct start {{ container_id }}"
  register: container_start_result
  tags: start

- name: "Warte bis Container vollstaendig gestartet ist"
  shell: "pct status {{ container_id }}"
  register: status_check
  until: "'running' in status_check.stdout"
  retries: "{{ container_start_retries }}"
  delay: "{{ container_start_delay }}"
  tags: start

- name: "Ermittle Container-IP-Adresse"
  shell: "pct exec {{ container_id }} -- ip addr show eth0 | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1 | head -1"
  register: container_ip_result
  failed_when: false
  changed_when: false
  tags: info

- name: "Sammle Container-Informationen"
  shell: "pct list | grep {{ container_id }}"
  register: container_info
  changed_when: false
  tags: info
