---
# Unify Network Registration - Template-basiert
- name: "Ermittle Container-MAC-Adresse"
  shell: "pct config {{ container_id }} | grep -E '^net0:' | grep -o 'hwaddr=[^,]*' | cut -d= -f2"
  register: container_mac_result
  changed_when: false
  tags: unify

- name: "Erstelle individualisiertes UniFi-Script"
  template:
    src: unify_update_container.sh.j2
    dest: /tmp/unify_update_{{ container_id }}.sh
    mode: '0755'
  when: container_mac_result.stdout != ""
  tags: unify

- name: "Kopiere Script direkt zum UniFi Controller"
  template:
    src: unify_update_container.sh.j2
    dest: /tmp/unify_update_{{ container_id }}.sh
    mode: '0755'
  delegate_to: unify
  when: container_mac_result.stdout != ""
  tags: unify

- name: "Führe UniFi-Registrierung aus"
  shell: "/tmp/unify_update_{{ container_id }}.sh"
  delegate_to: unify
  register: unify_update_result
  when: container_mac_result.stdout != ""
  tags: unify

- name: "Räume lokales temporäres Script auf"
  file:
    path: /tmp/unify_update_{{ container_id }}.sh
    state: absent
  when: container_mac_result.stdout != ""
  tags: unify

- name: "Räume remote temporäres Script auf"
  file:
    path: /tmp/unify_update_{{ container_id }}.sh
    state: absent
  delegate_to: unify
  when: container_mac_result.stdout != ""
  tags: unify

- name: "UniFi-Registrierung erfolgreich"
  debug:
    msg: "Container {{ container_hostname }} mit MAC {{ container_mac_result.stdout }} registriert"
  when:
    - container_mac_result.stdout != ""
    - unify_update_result is defined
    - unify_update_result.rc == 0
  tags: unify
