---
# UniFi Controller Integration - Einfache MongoDB-Registrierung
# Ohne API-Calls, nur direkte MongoDB-Befehle

- name: "COPY-PASTE BEFEHL FÜR REGISTRIERUNG"
  debug:
    msg: |
      ==========================================================================
      COPY-PASTE BEFEHL FÜR NAMENSÄNDERUNG (MongoDB):
      ==========================================================================

      Container: {{ container_hostname }}
      MAC-Adresse: {{ container_mac_result.stdout | lower }}

      ssh unifi 'mongo --port 27117 ace --eval "

      // Suche alle Clients mit dieser MAC
      var clients = db.user.find({\"mac\": \"{{ container_mac_result.stdout | lower }}\"}).toArray();

      print(\"Gefundene Clients mit MAC {{ container_mac_result.stdout | lower }}:\");

      if (clients.length > 0) {
        clients.forEach(function(client, index) {
          print(\"Client \" + (index + 1) + \":\");
          print(\"  Name: \" + client.name);
          print(\"  Device-ID: \" + client.device_id);
          print(\"  Site-ID: \" + client.site_id);
        });

        // Alle Clients mit dieser MAC umbenennen
        var result = db.user.updateMany(
          {\"mac\": \"{{ container_mac_result.stdout | lower }}\"},
          {\"\$set\": {
            \"name\": \"LXC-{{ container_hostname }}\",
            \"display_name\": \"LXC-{{ container_hostname }}\",
            \"hostname\": \"{{ container_hostname }}\",
            \"note\": \"Proxmox LXC Container ID {{ container_id }} - Updated {{ ansible_date_time.date }}\"
          }}
        );

        print(\"Update erfolgreich: \" + result.modifiedCount + \" Client(s) umbenannt zu: LXC-{{ container_hostname }}\");

        // Zeige aktuellen Zustand
        db.user.find({\"mac\": \"{{ container_mac_result.stdout | lower }}\"}).forEach(function(doc) {
          print(\"Neuer Name: \" + doc.name + \", MAC: \" + doc.mac);
        });

      } else {
        print(\"FEHLER: Kein Client mit MAC {{ container_mac_result.stdout | lower }} gefunden\");
        print(\"Tipp: Container starten und 5-10 Minuten warten, dann erneut versuchen\");
      }
      "'

      ssh unifi 'service unifi restart'

      ==========================================================================
  when:
    - container_mac_result is defined
    - container_mac_result.stdout != ""
  tags: [unifi_commands]
