# Unify Network Registration
# Registriert die Container-MAC-Adresse im Unify Controller

- name: "Ermittle Container-MAC-Adresse"
  shell: "pct config {{ container_id }} | grep -E '^net0:' | grep -o 'hwaddr=[^,]*' | cut -d= -f2"
  register: container_mac_result
  changed_when: false
  tags: unify

- name: "Setze Container-MAC als Variable"
  set_fact:
    container_mac: "{{ container_mac_result.stdout }}"
  tags: unify

- name: "Erstelle MongoDB-Registrierungs-Skript"
  template:
    src: unify_register.js.j2
    dest: /tmp/unify_register_{{ container_id }}.js
  delegate_to: unify
  become: false
  tags: unify

- name: "Registriere MAC-Adresse im Unify Controller"
  shell: "mongo --port 27117 /tmp/unify_register_{{ container_id }}.js"
  delegate_to: unify
  become: false
  register: unify_registration_result
  tags: unify

- name: "Debug: Unify Registration Ergebnis"
  debug:
    msg: |
      Unify Registration:
      - MAC: {{ container_mac }}
      - Name: {{ container_hostname }}
      - Ergebnis: {{ unify_registration_result.stdout }}
  when: enable_debug | default(false)
  tags: unify

- name: "Bereinige temporaeres Skript"
  file:
    path: /tmp/unify_register_{{ container_id }}.js
    state: absent
  delegate_to: unify
  become: false
  tags: unify
