---
# Manual UniFi Registration Commands

- name: "Ermittle Container-MAC-Adresse für manuellen UniFi-Eintrag"
  shell: "pct config {{ container_id }} | grep -E '^net0:' | grep -o 'hwaddr=[^,]*' | cut -d= -f2"
  register: container_mac_result
  changed_when: false
  tags: unify_manual

- name: "Zeige fertigen UniFi-Registrierungs-Befehl"
  debug:
    msg: |

      ===============================================
      MANUELLER UNIFI-REGISTRIERUNGS-BEFEHL
      ===============================================

      Container: {{ container_hostname }}
      Container-ID: {{ container_id }}
      MAC-Adresse: {{ container_mac_result.stdout }}

      FERTIGER COPY-PASTE BEFEHL:

      ssh unifi 'mongo --port 27117 ace --eval '\''
        db.user.update(
          {"mac": "{{ container_mac_result.stdout | lower }}"},
          {"$set": {
            "name": "{{ container_hostname }}",
            "dev_id_override": 5254,
            "network_members_group_ids": ["689247c7d3d4080f26122b2a"]
          }},
          {upsert: true}
        );
        db.user.find({"mac": "{{ container_mac_result.stdout | lower }}"}).pretty();
      '\'''

      ssh unifi service unifi restart

  when: container_mac_result.stdout != ""
  tags: unify_manual
