# Container-Validierung

- name: "Ueberpruefe Status der Container-ID {{ container_id }}"
  shell: "pct status {{ container_id }}"
  register: container_status
  failed_when: false
  changed_when: false
  tags: validation
